### ISSUE TITLE
特意登上来埋汰你的，你就是个祸害！

### ISSUE THREAD

**Issue by cc-ok200** [DyncKathline/ZxingScan#2]
从简书还是CSDN来着，看到这个库的软文，标题好像还是媲美微信啥的，现在想想估计那软文就是你自己写的。

不会做库就别做，集成用了半天，没这个产品思维也就算了，等运行一看布局全是错乱的，有的按钮太大了，有的按钮太小了，版式也错乱的很。再一看布局代码，我的天，图片你用TextView，文字你用ImageView，你牛，你真牛。

**Comment by DyncKathline** [comment]
来来来，你教我“文字你用ImageView”，你真的会Android吗？
