### ISSUE TITLE
问题太多了，还要解决重影问题。

### ISSUE THREAD

**Issue by cc-ok200** [DyncKathline/ZxingScan#3]
真是没有一点产品思维，重新布完局，activity里的ImageView, TextView类型要跟着改，改完运行下又发现：谁会把大红重新扫码按钮放出来，谁会把扫描结果默认显示出来。去掉后，还得解决扫码框重影问题，哎。我不活了，再见！！！

**Comment by DyncKathline** [comment]
你也是让我惊讶到了，我写这个只是写功能，难道要我教你写布局？

**Comment by DyncKathline** [comment]
逻辑都实现好了，布局也要帮你实现？
